### ISSUE TITLE
DlqRouteBuilder fails to deserialize DetectionResponse message

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#573]
On at least one occasion, we've observed that this code in DlqRouteBuilder.java generates an exception:

```
.pipeline()
   // deserialize protobuf message for readability
   .unmarshal().protobuf(DetectionProtobuf.DetectionRequest.getDefaultInstance()).convertBodyTo(String.class)
   .to(exitPoint) // send to the exit point to indicate it has been processed (and for auditing)
```

Exception:

```
2018-05-14 12:19:39,283 WARN [Camel (camelContext) thread #0 - JmsConsumer[ActiveMQ.DLQ]] o.a.c.c.jms.EndpointMessageListener - Execution of JMS message listener failed. Caused by: [org.apache.camel.RuntimeCamelException - com.google.protobuf.InvalidProtocolBufferException: Message missing required fields: data_uri]
org.apache.camel.RuntimeCamelException: com.google.protobuf.InvalidProtocolBufferException: Message missing required fields: data_uri
at org.apache.camel.util.ObjectHelper.wrapRuntimeCamelException(ObjectHelper.java:1642) ~[camel-core-2.16.2.jar:2.16.2]
at org.apache.camel.component.jms.EndpointMessageListener$EndpointMessageListenerAsyncCallback.done(EndpointMessageListener.java:195) ~[camel-jms-2.16.2.jar:2.16.2]
at org.apache.camel.component.jms.EndpointMessageListener.onMessage(EndpointMessageListener.java:116) ~[camel-jms-2.16.2.jar:2.16.2]
at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:721) ~[spring-jms-4.2.5.RELEASE.jar:4.2.5.RELEASE]
at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:681) ~[spring-jms-4.2.5.RELEASE.jar:4.2.5.RELEASE]
at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651) ~[spring-jms-4.2.5.RELEASE.jar:4.2.5.RELEASE]
at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315) [spring-jms-4.2.5.RELEASE.jar:4.2.5.RELEASE]
at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253) [spring-jms-4.2.5.RELEASE.jar:4.2.5.RELEASE]
at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1158) [spring-jms-4.2.5.RELEASE.jar:4.2.5.RELEASE]
at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1150) [spring-jms-4.2.5.RELEASE.jar:4.2.5.RELEASE]
at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1047) [spring-jms-4.2.5.RELEASE.jar:4.2.5.RELEASE]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_144]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_144]
at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]
Caused by: com.google.protobuf.InvalidProtocolBufferException: Message missing required fields: data_uri
at com.google.protobuf.UninitializedMessageException.asInvalidProtocolBufferException(UninitializedMessageException.java:81) ~[protobuf-java-2.6.1.jar:na]
at com.google.protobuf.AbstractParser.checkMessageInitialized(AbstractParser.java:71) ~[protobuf-java-2.6.1.jar:na]
at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:168) ~[protobuf-java-2.6.1.jar:na]
at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:180) ~[protobuf-java-2.6.1.jar:na]
at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:185) ~[protobuf-java-2.6.1.jar:na]
at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49) ~[protobuf-java-2.6.1.jar:na]
at org.mitre.mpf.wfm.buffers.DetectionProtobuf$DetectionRequest.parseFrom(DetectionProtobuf.java:8502) ~[mpf-protobuf-1.0.0.jar:na]
at org.mitre.mpf.wfm.camel.operations.detection.BaseDetectionStatusProcessor.process(BaseDetectionStatusProcessor.java:42) ~[BaseDetectionStatusProcessor.class:na]
at org.mitre.mpf.wfm.camel.operations.detection.DetectionDeadLetterProcessor.process(DetectionDeadLetterProcessor.java:42) ~[DetectionDeadLetterProcessor.class:na]
at org.apache.camel.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:63) ~[camel-core-2.16.2.jar:2.16.2]
at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77) ~[camel-core-2.16.2.jar:2.16.2]
at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:460) ~[camel-core-2.16.2.jar:2.16.2]
at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190) ~[camel-core-2.16.2.jar:2.16.2]
at org.apache.camel.processor.Pipeline.process(Pipeline.java:121) ~[camel-core-2.16.2.jar:2.16.2]
at org.apache.camel.processor.Pipeline.process(Pipeline.java:83) ~[camel-core-2.16.2.jar:2.16.2]
at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77) ~[camel-core-2.16.2.jar:2.16.2]
at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190) ~[camel-core-2.16.2.jar:2.16.2]
at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:460) ~[camel-core-2.16.2.jar:2.16.2]
at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190) ~[camel-core-2.16.2.jar:2.16.2]
at org.apache.camel.processor.MulticastProcessor.doProcessSequential(MulticastProcessor.java:668) ~[camel-core-2.16.2.jar:2.16.2]
at org.apache.camel.processor.MulticastProcessor.doProcessSequential(MulticastProcessor.java:596) ~[camel-core-2.16.2.jar:2.16.2]
at org.apache.camel.processor.MulticastProcessor.process(MulticastProcessor.java:237) ~[camel-core-2.16.2.jar:2.16.2]
at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77) ~[camel-core-2.16.2.jar:2.16.2]
at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190) ~[camel-core-2.16.2.jar:2.16.2]
at org.apache.camel.processor.Pipeline.process(Pipeline.java:121) ~[camel-core-2.16.2.jar:2.16.2]
at org.apache.camel.processor.Pipeline.process(Pipeline.java:83) ~[camel-core-2.16.2.jar:2.16.2]
at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190) ~[camel-core-2.16.2.jar:2.16.2]
at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109) ~[camel-core-2.16.2.jar:2.16.2]
at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:87) ~[camel-core-2.16.2.jar:2.16.2]
at org.apache.camel.component.jms.EndpointMessageListener.onMessage(EndpointMessageListener.java:112) ~[camel-jms-2.16.2.jar:2.16.2]
... 11 common frames omitted
```

It seems that for some reason, we're trying to deserialize a DetectionResponse as a DetectionRequest. Note that in the above scenario, AMQ was duplicating many DetectionResponse messages. We may have failed to deserialize a duplicate.

**Comment by jrobble** [comment]
I believe the message that caused the exception was a DetectionResponse, and the reason it looks a little different than expected is because it’s a DetectionResponse signaling an MPF error, so it doesn’t contain any tracks or the “FACE” data type field. That would explain why it’s so short.
