### ISSUE TITLE
Streaming summary report not delivered due to "Unable to locate streaming job with id"

### ISSUE THREAD

**Issue by jrobble** [openmpf/openmpf#966]
I performed some tests where each time I ran streaming job and terminated the stream while the job was in progress. The first time I encountered this issue. I was not able to recreate it after 2 more attempts.

The Final health report was good:

```
{"reportDate":"2019-09-05T12:13:32.367023-04:00","reports":[{"jobId":781,"externalId":null,"jobStatus":"TERMINATED","jobStatusDetail":"Stream stalled for too long. It is no longer possible to read frames.","activityFrameId":"8","activityTimestamp":"2019-09-05T12:11:50.409-04:00"}]}
```

However, **no summary report was sent**. It should have been something like:

```
{"reportDate":"2019-09-05T12:26:36.212354-04:00","jobId":783,"externalId":null,"segmentId":16,"segmentStartFrame":160,"segmentStopFrame":162,"errorMessage":"It is no longer possible to read frames.","output":{"NO TRACKS":[]}}
```

Here's the WFM log:

```
05-Sep-2019 11:19:33.458 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
05-Sep-2019 11:19:33.587 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
05-Sep-2019 11:19:33.603 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 300463 ms
2019-09-05 12:11:48,880 INFO [http-nio-8080-exec-7] o.m.m.w.d.InProgressStreamingJobsService - Initializing streaming job 781 which will run the "CUSTOM FACE DETECTION PIPELINE" pipeline
2019-09-05 12:11:49,097 INFO [http-nio-8080-exec-7] o.m.m.n.s.MasterStreamingJobManager - Sending LaunchStreamingJobMessage for job 781 to node openmpf-master.mshome.net
2019-09-05 12:11:50,201 INFO [Camel (camelContext) thread #4 - JmsConsumer[MPF.WFM_STREAMING_JOB_STATUS]] o.m.m.w.d.InProgressStreamingJobsService - Setting status of job 781 to IN_PROGRESS.
2019-09-05 12:11:50,460 INFO [Camel (camelContext) thread #7 - JmsConsumer[MPF.WFM_STREAMING_JOB_ACTIVITY]] o.m.m.w.d.InProgressStreamingJobsService - Setting last activity of job 781 to frame 8 at time 2019-09-05T12:11:50.409-04:00
2019-09-05 12:11:54,172 WARN [I/O dispatcher 1] o.m.m.w.u.CallbackUtils - Sent health report(s) callback to http://localhost:2000 for job ids [781]. Receiver did not respond.
2019-09-05 12:11:55,209 WARN [I/O dispatcher 2] o.m.m.w.u.CallbackUtils - Sent health report(s) callback to http://localhost:2000 for job ids [781]. Receiver did not respond.
2019-09-05 12:11:55,468 WARN [I/O dispatcher 3] o.m.m.w.u.CallbackUtils - Sent health report(s) callback to http://localhost:2000 for job ids [781]. Receiver did not respond.
2019-09-05 12:11:57,901 WARN [I/O dispatcher 4] o.m.m.w.u.CallbackUtils - Sent health report(s) callback to http://localhost:2000 for job ids [781]. Receiver did not respond.
2019-09-05 12:12:27,910 WARN [I/O dispatcher 1] o.m.m.w.u.CallbackUtils - Sent health report(s) callback to http://localhost:2000 for job ids [781]. Receiver did not respond.
2019-09-05 12:12:57,910 WARN [I/O dispatcher 2] o.m.m.w.u.CallbackUtils - Sent health report(s) callback to http://localhost:2000 for job ids [781]. Receiver did not respond.
2019-09-05 12:13:27,916 WARN [I/O dispatcher 3] o.m.m.w.u.CallbackUtils - Sent health report(s) callback to http://localhost:2000 for job ids [781]. Receiver did not respond.
2019-09-05 12:13:32,366 INFO [jgroups-19,MPF_Channel,MasterNode:openmpf-master.mshome.net:MPF-MasterNode] o.m.m.n.s.MasterStreamingJobManager - Job 781 has exited.
2019-09-05 12:13:32,366 INFO [jgroups-19,MPF_Channel,MasterNode:openmpf-master.mshome.net:MPF-MasterNode] o.m.m.w.n.NodeManagerStatus - Streaming job 781 exited due to STREAM_STALLED.
2019-09-05 12:13:32,366 INFO [jgroups-19,MPF_Channel,MasterNode:openmpf-master.mshome.net:MPF-MasterNode] o.m.m.w.d.InProgressStreamingJobsService - Setting status of job 781 to TERMINATED: Stream stalled for too long. It is no longer possible to read frames..
2019-09-05 12:13:32,400 INFO [jgroups-19,MPF_Channel,MasterNode:openmpf-master.mshome.net:MPF-MasterNode] o.m.m.w.d.InProgressStreamingJobsService - Clearing all job information for job 781
2019-09-05 12:13:32,401 INFO [jgroups-19,MPF_Channel,MasterNode:openmpf-master.mshome.net:MPF-MasterNode] o.m.m.w.b.i.StreamingJobRequestServiceImpl - [Streaming Job 781:*:*] Streaming Job complete!
2019-09-05 12:13:32,639 ERROR [Camel (camelContext) thread #9 - JmsConsumer[MPF.WFM_STREAMING_JOB_SUMMARY_REPORTS]] o.a.c.p.DefaultErrorHandler - Failed delivery for (MessageId: queue_MPF.WFM_STREAMING_JOB_SUMMARY_REPORTS_ID_openmpf-master-37898-1567699909221-0_0_1_3_1 on ExchangeId: ID-openmpf-master-41098-1567696497613-0-3). Exhausted after delivery attempt: 1 caught: org.mitre.mpf.wfm.WfmProcessingException: Unable to locate streaming job with id: 781

Message History
---------------------------------------------------------------------------------------------------------------------------------------
RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
[Streaming Job Summ] [Streaming Job Summ] [jms://MPF.WFM_STREAMING_JOB_SUMMARY_REPORTS                                   ] [       114]
[Streaming Job Summ] [log3              ] [log                                                                           ] [         0]
[Streaming Job Summ] [unmarshal1        ] [unmarshal[org.apache.camel.model.DataFormatDefinition@244a94dc]               ] [        87]
[Streaming Job Summ] [process5          ] [Processor@0xa4a3450                                                           ] [        24]

Exchange
---------------------------------------------------------------------------------------------------------------------------------------
Exchange[
	Id                  ID-openmpf-master-41098-1567696497613-0-3
	ExchangePattern     InOnly
	Headers             {breadcrumbId=ID:openmpf-master-37898-1567699909221-0:0:1:3:1, CamelRedelivered=false, CamelRedeliveryCounter=0, JMSCorrelationID=null, JMSCorrelationIDAsBytes=null, JMSDeliveryMode=2, JMSDestination=queue://MPF.WFM_STREAMING_JOB_SUMMARY_REPORTS, JMSExpiration=0, JMSMessageID=ID:openmpf-master-37898-1567699909221-0:0:1:3:1, JMSPriority=4, JMSRedelivered=false, JMSReplyTo=null, JMSTimestamp=1567700012312, JMSType=null, JMSXGroupID=null, JMSXUserID=null, JOB_ID=781}
	BodyType            org.mitre.mpf.wfm.buffers.DetectionProtobuf.StreamingDetectionResponse
	Body                error: "It is no longer possible to read frames."segment_number: 0segment_start_frame: 0segment_stop_frame: 157detection_type: "FACE"video_tracks {  start_frame: 8  start_time: 1567699910409  stop_frame: 77  stop_time: 1567699946439  confidence: 7.44119  detections {    frame_number: 8    time: 1567699910409    x_left_upper: 74    y_left_upper: 110    width: 70    height: 87    confidence: 1.9644439  }  detections {    frame_number: 9    time: 1567699910454    x_left_upper: 73    y_left_upper: 106    width: 70    height: 87    confidence: 5.2962794  }  detections {    frame_number: 10    time: 1567699910533    x_left_upper: 71    y_left_upper: 104    width: 70    height: 87    confidence: 6.0082555  }  detections {    frame_number: 11    time: 1567699910608    x_left_upper: 69    y_left_upper: 100    width: 70    height: 87    confidence: 5.291494  }  detections {    frame_number: 12    time: 1567699910697    x_left_upper: 68    y_left_upper: 97    width: 70    height: 87    confidence: 6.376634  }  detections {    frame_number: 13    time: 1567699910782    x_left_upper: 68    y_left_upper: 97    width: 70    height: 87    confidence: 5.2936015  }  detections {    frame_number: 14    time: 1567699910863    x_left_upper: 68    y_left_upper: 96    width: 70    height: 87    confidence: 5.9561515  }  detections {    frame_number: 15    time: 1567699910949    x_left_upper: 69    y_left_upper: 95    width: 70    height: 87    confidence: 5.497817  }  detections {    frame_number: 16    time: 1567699911033    x_left_upper: 71    y_left_upper: 92    width: 70    height: 87    confidence: 5.783502  }  detections {    frame_number: 17    time: 1567699911128    x_left_upper: 73    y_left_upper: 90    width: 70    height: 87    confidence: 5.6092105  }  detections {    frame_number: 18    time: 1567699911223    x_left_upper: 76    y_left_upper: 87    width: 70    height: 87    confidence: 4.9625454  }  detections {    frame_number: 19    time: 1567699911299    x_left_upper: 78    y_left_upper: 84    width: 69    height: 87    confidence: 6.072695  }  detections {    frame_number: 20    time: 1567699911395    x_left_upper: 79    y_left_upper: 81    width: 69    height: 87    confidence: 6.017152  }  detections {    frame_number: 21    time: 1567699911479    x_left_upper: 80    y_left_upper: 79    width: 69    height: 86    confidence: 4.865711  }  detections {    frame_number: 22    time: 1567699911566    x_left_upper: 82    y_left_upper: 77    width: 69    height: 86    confidence: 5.7431407  }  detections {    frame_number: 23    time: 1567699911658    x_left_upper: 85    y_left_upper: 76    width: 69    height: 86    confidence: 6.495558  }  detections {    frame_number: 24    time: 1567699911753    x_left_upper: 89    y_left_upper: 75    width: 69    height: 86    confidence: 5.8995786  }  detections {    frame_number: 25    time: 1567699911847    x_left_upper: 93    y_left_upper: 74    width: 69    height: 87    confidence: 6.611317  }  detections {    frame_number: 26    time: 1567699911934    x_left_upper: 99    y_left_upper: 74    width: 69    height: 87    confidence: 5.3930383  }  detections {    frame_number: 27    time: 1567699912028    x_left_upper: 107    y_left_upper: 75    width: 69    height: 87    confidence: 5.556073  }  detections {    frame_number: 28    time: 1567699912119    x_left_upper: 116    y_left_upper: 76    width: 69    height: 87    confidence: 5.756424  }  detections {    frame_number: 29    time: 1567699912190    x_left_upper: 127    y_left_upper: 77    width: 70    height: 87    confidence: 4.4134984  }  detections {    frame_number: 30    time: 1567699912245    x_left_upper: 138    y_left_upper: 79    width: 70    height: 87    confidence: 4.882001  }  detections {    frame_number: 31    time: 1567699912315    x_left_upper: 148    y_left_upper: 81    width: 70    height: 87    confidence: 5.7430205  }  detections {    frame_number: 32    time: 1567699912386    x_left_upper: 156    y_left_upper: 81    width: 70    height: 87    confidence: 5.344711  }  detections {    frame_number: 33    time: 1567699912458    x_left_upper: 162    y_left_upper: 81    width: 70    height: 87    confidence: 5.802184  }  detections {    frame_number: 34    time: 1567699912534    x_left_upper: 166    y_left_upper: 79    width: 70    height: 88    confidence: 5.603063  }  detections {    frame_number: 35    time: 1567699912599    x_left_upper: 167    y_left_upper: 75    width: 70    height: 88    confidence: 6.8478746  }  detections {    frame_number: 36    time: 1567699912679    x_left_upper: 167    y_left_upper: 71    width: 70    height: 88    confidence: 5.6937227  }  detections {    frame_number: 37    time: 1567699912759    x_left_upper: 166    y_left_upper: 67    width: 70    height: 88    confidence: 4.871994  }  detections {    frame_number: 38    time: 1567699912849    x_left_upper: 164    y_left_upper: 63    width: 70    height: 88    confidence: 6.127113  }  detections {    frame_number: 39    time: 1567699912941    x_left_upper: 161    y_left_upper: 60    width: 70    height: 88    confidence: 4.601139  }  detections {    frame_number: 40    time: 1567699913033    x_left_upper: 157    y_left_upper: 58    width: 70    height: 88    confidence: 6.0058436  }  detections {    frame_number: 41    time: 1567699913129    x_left_upper: 151    y_left_upper: 57    width: 70    height: 88    confidence: 5.4989357  }  detections {    frame_number: 42    time: 1567699913220    x_left_upper: 145    y_left_upper: 57    width: 70    height: 88    confidence: 5.5665145  }  detections {    frame_number: 43    time: 1567699913306    x_left_upper: 138    y_left_upper: 59    width: 70    height: 88    confidence: 4.5805855  }  detections {    frame_number: 44    time: 1567699913383    x_left_upper: 132    y_left_upper: 62    width: 70    height: 88    confidence: 4.7976522  }  detections {    frame_number: 45    time: 1567699913466    x_left_upper: 125    y_left_upper: 63    width: 73    height: 92    confidence: 4.906245  }  detections {    frame_number: 46    time: 1567699913550    x_left_upper: 121    y_left_upper: 65    width: 77    height: 96    confidence: 5.071772  }  detections {    frame_number: 47    time: 1567699913657    x_left_upper: 120    y_left_upper: 65    width: 80    height: 100    confidence: 5.0638165  }  detections {    frame_number: 48    time: 1567699913735    x_left_upper: 113    y_left_upper: 70    width: 84    height: 105    confidence: 4.3710203  }  detections {    frame_number: 49    time: 1567699913802    x_left_upper: 107    y_left_upper: 75    width: 88    height: 109    confidence: 1.4217963  }  detections {    frame_number: 63    time: 1567699944967    x_left_upper: 101    y_left_upper: 80    width: 92    height: 114    confidence: 6.5803256  }  detections {    frame_number: 64    time: 1567699945097    x_left_upper: 94    y_left_upper: 85    width: 96    height: 120    confidence: 7.44119  }  detections {    frame_number: 65    time: 1567699945227    x_left_upper: 86    y_left_upper: 91    width: 101    height: 126    confidence: 6.5846834  }  detections {    frame_number: 66    time: 1567699945349    x_left_upper: 86    y_left_upper: 91    width: 106    height: 132    confidence: 7.375778  }  detections {    frame_number: 67    time: 1567699945478    x_left_upper: 86    y_left_upper: 91    width: 111    height: 138    confidence: 6.708384  }  detections {    frame_number: 68    time: 1567699945590    x_left_upper: 87    y_left_upper: 90    width: 116    height: 145    confidence: 6.6347537  }  detections {    frame_number: 69    time: 1567699945697    x_left_upper: 92    y_left_upper: 91    width: 116    height: 144    confidence: 6.867675  }  detections {    frame_number: 70    time: 1567699945821    x_left_upper: 100    y_left_upper: 93    width: 116    height: 145    confidence: 6.90158  }  detections {    frame_number: 71    time: 1567699945926    x_left_upper: 110    y_left_upper: 96    width: 116    height: 143    confidence: 6.065959  }  detections {    frame_number: 72    time: 1567699946014    x_left_upper: 123    y_left_upper: 102    width: 116    height: 137    confidence: 6.23807  }  detections {    frame_number: 73    time: 1567699946115    x_left_upper: 138    y_left_upper: 109    width: 117    height: 130    confidence: 5.8789706  }  detections {    frame_number: 74    time: 1567699946209    x_left_upper: 154    y_left_upper: 118    width: 117    height: 121    confidence: 5.802877  }  detections {    frame_number: 75    time: 1567699946298    x_left_upper: 171    y_left_upper: 129    width: 117    height: 110    confidence: 5.346552  }  detections {    frame_number: 76    time: 1567699946379    x_left_upper: 180    y_left_upper: 134    width: 117    height: 105    confidence: 3.4292727  }  detections {    frame_number: 77    time: 1567699946439    x_left_upper: 188    y_left_upper: 140    width: 117    height: 99    confidence: 0.9835448  }}video_tracks {  start_frame: 50  start_time: 1567699913845  stop_frame: 54  stop_time: 1567699914050  confidence: 4.4263115  detections {    frame_number: 50    time: 1567699913845    x_left_upper: 186    y_left_upper: 48    width: 72    height: 90    confidence: 3.7421443  }  detections {    frame_number: 51    time: 1567699913910    x_left_upper: 195    y_left_upper: 45    width: 72    height: 90    confidence: 4.4263115  }  detections {    frame_number: 52    time: 1567699913965    x_... [Body clipped after 10000 chars, total length is 22042]
]

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------
org.mitre.mpf.wfm.WfmProcessingException: Unable to locate streaming job with id: 781
	at org.mitre.mpf.wfm.data.InProgressStreamingJobsService.getJobImpl(InProgressStreamingJobsService.java:105) ~[classes/:?]
	at org.mitre.mpf.wfm.data.InProgressStreamingJobsService.getJob(InProgressStreamingJobsService.java:96) ~[classes/:?]
	at org.mitre.mpf.wfm.businessrules.impl.StreamingJobRequestServiceImpl.handleNewSummaryReport(StreamingJobRequestServiceImpl.java:471) ~[classes/:?]
	at org.mitre.mpf.wfm.camel.routes.StreamingJobRoutesBuilder.lambda$configure$2(StreamingJobRoutesBuilder.java:111) ~[classes/:?]
	at org.apache.camel.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:63) ~[camel-core-2.16.2.jar:2.16.2]
	at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77) ~[camel-core-2.16.2.jar:2.16.2]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:460) ~[camel-core-2.16.2.jar:2.16.2]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190) ~[camel-core-2.16.2.jar:2.16.2]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:121) ~[camel-core-2.16.2.jar:2.16.2]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:83) ~[camel-core-2.16.2.jar:2.16.2]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190) ~[camel-core-2.16.2.jar:2.16.2]
	at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109) ~[camel-core-2.16.2.jar:2.16.2]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:87) ~[camel-core-2.16.2.jar:2.16.2]
	at org.apache.camel.component.jms.EndpointMessageListener.onMessage(EndpointMessageListener.java:112) ~[camel-jms-2.16.2.jar:2.16.2]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:721) ~[spring-jms-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:681) ~[spring-jms-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651) ~[spring-jms-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315) ~[spring-jms-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253) ~[spring-jms-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1158) ~[spring-jms-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1150) ~[spring-jms-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1047) ~[spring-jms-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2019-09-05 12:13:32,641 WARN [Camel (camelContext) thread #9 - JmsConsumer[MPF.WFM_STREAMING_JOB_SUMMARY_REPORTS]] o.a.c.c.j.EndpointMessageListener - Execution of JMS message listener failed. Caused by: [org.apache.camel.RuntimeCamelException - org.mitre.mpf.wfm.WfmProcessingException: Unable to locate streaming job with id: 781]
org.apache.camel.RuntimeCamelException: org.mitre.mpf.wfm.WfmProcessingException: Unable to locate streaming job with id: 781
	at org.apache.camel.util.ObjectHelper.wrapRuntimeCamelException(ObjectHelper.java:1642) ~[camel-core-2.16.2.jar:2.16.2]
	at org.apache.camel.component.jms.EndpointMessageListener$EndpointMessageListenerAsyncCallback.done(EndpointMessageListener.java:195) ~[camel-jms-2.16.2.jar:2.16.2]
	at org.apache.camel.component.jms.EndpointMessageListener.onMessage(EndpointMessageListener.java:116) ~[camel-jms-2.16.2.jar:2.16.2]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:721) ~[spring-jms-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:681) ~[spring-jms-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:651) ~[spring-jms-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:315) ~[spring-jms-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:253) ~[spring-jms-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1158) ~[spring-jms-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1150) ~[spring-jms-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1047) ~[spring-jms-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: org.mitre.mpf.wfm.WfmProcessingException: Unable to locate streaming job with id: 781
	at org.mitre.mpf.wfm.data.InProgressStreamingJobsService.getJobImpl(InProgressStreamingJobsService.java:105) ~[classes/:?]
	at org.mitre.mpf.wfm.data.InProgressStreamingJobsService.getJob(InProgressStreamingJobsService.java:96) ~[classes/:?]
	at org.mitre.mpf.wfm.businessrules.impl.StreamingJobRequestServiceImpl.handleNewSummaryReport(StreamingJobRequestServiceImpl.java:471) ~[classes/:?]
	at org.mitre.mpf.wfm.camel.routes.StreamingJobRoutesBuilder.lambda$configure$2(StreamingJobRoutesBuilder.java:111) ~[classes/:?]
	at org.apache.camel.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:63) ~[camel-core-2.16.2.jar:2.16.2]
	at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77) ~[camel-core-2.16.2.jar:2.16.2]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:460) ~[camel-core-2.16.2.jar:2.16.2]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190) ~[camel-core-2.16.2.jar:2.16.2]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:121) ~[camel-core-2.16.2.jar:2.16.2]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:83) ~[camel-core-2.16.2.jar:2.16.2]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190) ~[camel-core-2.16.2.jar:2.16.2]
	at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109) ~[camel-core-2.16.2.jar:2.16.2]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:87) ~[camel-core-2.16.2.jar:2.16.2]
	at org.apache.camel.component.jms.EndpointMessageListener.onMessage(EndpointMessageListener.java:112) ~[camel-jms-2.16.2.jar:2.16.2]
	... 11 more
2019-09-05 12:13:37,372 WARN [I/O dispatcher 4] o.m.m.w.u.CallbackUtils - Sent health report(s) callback to http://localhost:2000 for job ids [781]. Receiver did not respond.
```

**Comment by brosenberg42** [comment]
Currently, we use separate queues for streaming job status messages, activity alerts, and summary reports. We probably need to use the same queue for all of those message types to ensure they are processed in order.
